### ISSUE TITLE
undefined reference in opcodes.c

### ISSUE THREAD

**Issue by YoYo1846** [dgrubb/STM6502#1]
When compiling the project in Em::Blocks, some undefined references are raised when trying to create the binary
Example
```
...\STM32F429\Emu_6510/opcodes.c:34: undefined reference to `ISA_table'
...\STM32F429\Emu_6510/opcodes.c:34: undefined reference to `opcode_ILL'
```

ISA_table is referenced in opcodes.h as an external (extern instruction_t ISA_table[ISA_LENGTH];), but not available in the project. => Something is missing in your project ?

**Comment by dgrubb** [comment]
Hi YoYo, thanks for taking a look at my project.

Yes. I'm afraid there's a great deal missing here as the code in this repository was just the beginnings of a loose sketch. What I did complete became a part of the HiFive-2600 project instead, where the 6502 emulation is a smaller part of a much larger project.

Part of me is inclined to return here and finish, but that's not going to happen for quite a while until I get some other projects off the back-burner. 

Cheers!

**Comment by YoYo1846** [comment]
Hey David,

Thanks for the clarification. For sure, the 2600 project answers the issue raised.

I was having a look on a way to swap my faulty 6510 on my C64 with a 'what I had' HW, powerfull enough (STM32 discovery), a little bit like this 

https://hackaday.com/2016/07/02/the-dual-core-arm-powered-commodore-64/

but no SW was available; so I decided to make my own, re-using what was already written on the subject.

This other single project might be an alternative, since it looks not so hard to map pc/data on some io pins with a few additionnal work (except trimming the timings).
https://github.com/jeelabs/embello/tree/master/projects/ask/emu6502

Have fun and I hope you're safe in Texas considering the disaster we can see on TV.

KR,
Lionel.
